### ISSUE TITLE
 Unable to login after upgrade from 2.3.5 to 2.4

### ISSUE THREAD

**Issue by stephgosling** [SUSE/Portus#1999]
### Description

Unable to login after upgrade from 2.3.5 to 2.4. Don't see any migrations to run (or didn't see any?)
Reverting to 2.3 and it works again (interesting other thing, both 2.3.5 and 2.3.6 refer to themselves as 2.3.5 in the footer, tho when running 2.3.6 the git sha is correct)

### Steps to reproduce

0. Stop and remove existing portus containers and volume via `docker-compose stop` and `docker-compose down` , `docker volume rm portus_static`
1. Bump portus versions in docker-compose.yml to 2.4 for portus and the background containers
2. Start stack
3. Background_1 exits with the following error (it behaves different differently to 2.3 in this respect)
```
background_1  | `Registry synchronization` was disabled because strategy is set to 'initial' and the database is not empty
background_1  | [Initialization] Running: 'Registry events', 'Garbage collector'
background_1  | /srv/Portus/lib/portus/background/garbage_collector.rb:55:in `older_than': undefined method `[]' for nil:NilClass (NoMethodError)
background_1  | 	from /srv/Portus/lib/portus/background/garbage_collector.rb:47:in `tags_to_be_collected'
background_1  | 	from /srv/Portus/lib/portus/background/garbage_collector.rb:18:in `work?'
background_1  | 	from /srv/Portus/bin/background.rb:58:in `block (2 levels) in <top (required)>'
background_1  | 	from /srv/Portus/bin/background.rb:56:in `each'
background_1  | 	from /srv/Portus/bin/background.rb:56:in `each_with_index'
background_1  | 	from /srv/Portus/bin/background.rb:56:in `block in <top (required)>'
background_1  | 	from /srv/Portus/bin/background.rb:55:in `loop'
background_1  | 	from /srv/Portus/bin/background.rb:55:in `<top (required)>'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `load'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `<top (required)>'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:90:in `runner'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
background_1  | 	from bin/rails:12:in `require'
background_1  | 	from bin/rails:12:in `<main>'
background_1  | exit status 1
```
On navigating to the web interface I get a 500 (albeit a themed one):
```
portus_1      |   Rendered dashboard/index.html.slim within layouts/application (221.7ms)
portus_1      |   Rendered shared/_config.html.slim (3.6ms)
portus_1      | Completed 401 Unauthorized in 312ms (ActiveRecord: 38.8ms)
portus_1      | 
portus_1      | ActionView::Template::Error (undefined method `[]' for nil:NilClass):
portus_1      |     1: javascript:
portus_1      |     2:   window.API_URL = '//#{app_path}';
portus_1      |     3:   window.PAGINATION = {
portus_1      |     4:     limit: #{pagination_limit},
portus_1      |     5:     beforeAfter: #{pagination_before_after}
portus_1      |     6:   };
portus_1      |   app/helpers/application_helper.rb:60:in `pagination_limit'
portus_1      |   app/views/shared/_config.html.slim:4:in `_app_views_shared__config_html_slim___2667011782284473101_35064980'
portus_1      |   app/views/layouts/application.html.slim:31:in `_app_views_layouts_application_html_slim__2518048766129532383_41454580'
portus_1      |   app/middleware/catch_json_parse_errors.rb:11:in `call'
portus_1      | 
portus_1      | 
portus_1      | Processing by ErrorsController#show as HTML
portus_1      |   Parameters: {"status"=>"500"}
portus_1      |   Rendered errors/500.html.erb within layouts/errors (0.9ms)
portus_1      |   Rendered errors/_status_title.html.slim (2.1ms)
portus_1      | Completed 500 Internal Server Error in 28ms (Views: 27.1ms | ActiveRecord: 0.0ms)
```

### Deployment information
Deployment is via docker-compose though the nginx frontend is in a different compose stack

```
version: "3"

services:
  portus:
    image: opensuse/portus:2.4
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      # SSL
      - PORTUS_PUMA_TLS_KEY=/certificates/portus.key
      - PORTUS_PUMA_TLS_CERT=/certificates/portus.crt

      # NGinx is serving the assets instead of Puma. If you want to change this,
      # uncomment this line.
      #- RAILS_SERVE_STATIC_FILES='true'
    ports:
      - 3000:3000
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro
      - ./portus/config.yml:/srv/Portus/config/config.yml
      - static:/srv/Portus/public

  background:
    image: opensuse/portus:2.4
    depends_on:
      - portus
      - db
    environment:
      # Theoretically not needed, but cconfig's been buggy on this...
      - CCONFIG_PREFIX=PORTUS
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      - PORTUS_BACKGROUND=true
    links:
      - db
    volumes:
      - ./portus/config.yml:/srv/Portus/config/config.yml
      - ./secrets:/certificates:ro

  db:
    image: library/mariadb:10.0.23
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      - MYSQL_DATABASE=portus_production

      # Again, the password shouldn't be handled like this.
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - /var/lib/portus/mariadb:/var/lib/mysql

  registry:
    image: library/registry:2.6
    command: ["/bin/sh", "/etc/docker/registry/init"]
    environment:
      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: https://${MACHINE_FQDN}/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /secrets/portus.crt

      # SSL
      REGISTRY_HTTP_TLS_CERTIFICATE: /secrets/portus.crt
      REGISTRY_HTTP_TLS_KEY: /secrets/portus.key

      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://${MACHINE_FQDN}/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    volumes:
      - /var/lib/portus/registry:/var/lib/registry
      - ./secrets:/secrets:ro
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
      - ./registry/init:/etc/docker/registry/init:ro
    ports:
      - 5000:5000
      - 5001:5001 # required to access debug service
    links:
      - portus:portus

volumes:
  static:
    driver: local
```

**Configuration**:
```
[Mailer config] Host:     registry.mydomain.org
[Mailer config] Protocol: https://
Evaluated configuration:
---
email:
  from: portus@mydomain.org
  name: Portus
  reply_to: no-reply@mydomain.org
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    domain: example.com
    ssl_tls: ''
    enable_starttls_auto: false
    openssl_verify_mode: none
    ca_path: ''
    ca_file: ''
    user_name: ''
    password: "****"
    authentication: login
gravatar:
  enabled: true
delete:
  enabled: true
ldap:
  enabled: false
oauth:
  google_oauth2:
    enabled: false
  open_id:
    enabled: false
  github:
    enabled: true
    client_id: foo
    client_secret: bar
    organization: baz
    team: ''
    domain: ''
  gitlab:
    enabled: false
  bitbucket:
    enabled: false
first_user_admin:
  enabled: true
signup:
  enabled: false
check_ssl_usage:
  enabled: true
registry:
  jwt_expiration_time:
    value: 15
  catalog_page:
    value: 100
  timeout:
    value: 2
  read_timeout:
    value: 120
machine_fqdn:
  value: registry.mydomain.org
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: true
  create_team:
    enabled: true
  manage_team:
    enabled: true
  create_namespace:
    enabled: true
  manage_namespace:
    enabled: true
  create_webhook:
    enabled: true
  manage_webhook:
    enabled: true
  push_images:
    policy: allow-teams
security:
  clair:
    server: ''
    health_port: 6061
    timeout: 900
  zypper:
    server: ''
  dummy:
    server: ''
anonymous_browsing:
  enabled: true
background:
  registry:
    enabled: true
  sync:
    enabled: true
    strategy: initial

Portus version: 2.4.0@2.4.0
```

**Comment by stephgosling** [comment]
@vitoravelino amazing thank you! I thought I'd merged the configs cleanly but clearly not. Copied the stock config.yml and read through it, now 2.4 starts cleanly; looks like the GC stuff was the blocker.
